image: docker:latest

stages:
  - lint
  - build

.lint:
  stage: lint
  image: stangirard/pre-commit-terraform:0.12.29-1
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pre-commit run -a

.build-deploy:
  stage: build
  services:
    - name: docker:dind
  before_script:
    - chmod +x bin/build.sh
    - apk add --update curl jq && rm -rf /var/cache/apk/*
  script:
    - ./bin/build.sh

##Jobs ###

Precommit Verification:
  extends:
    - .lint

Build & Deploy Images:
  extends:
    - .build-deploy
  only:
    refs:
      - master
