name: Precommit

on:
  push:
    # run only against tags
    tags:
      - '*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1.2.3]
    name: build - ${{ matrix.version }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        uses: actions/checkout@v3
        name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Build and push Terraform:${{ matrix.version }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.version }}
          push: true
          tags: stangirard/pre-commit-terraform:${{ matrix.version }}-${{ steps.vars.outputs.tag }}, stangirard/pre-commit-terraform:${{ matrix.version }}-latest
          build-args: |
            RELEASE=${{ matrix.version }}
