name: Build & Push Docker Images

on:
  push:
    # run only against tags
    tags:
      - 'v*'

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:

  build:
    runs-on: ubuntu-latest
    environment: production

    strategy:
      matrix:
        version: [1.2.3, 1.2.2, 1.2.1, 1.2.0]
    name: build - ${{ matrix.version }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            stangirard/pre-commit-terraform
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=${{ matrix.version }}-{{version}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Terraform:${{ matrix.version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            RELEASE=${{ matrix.version }}
